# Generated by Django 3.2.17 on 2023-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=150)),
                ('Designation', models.CharField(max_length=150)),
            ],
        ),
    ]
